---
title: "TWAS"
author: "Jack Humphrey"
date: "2024-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggrepel)
```

```{r}
# twas_files <- list.files( pattern = "*fusion_res.tsv", recursive = TRUE, full.names = TRUE)
# names(twas_files) <- basename(twas_files)
# 
# d <- map_df(twas_files, read_tsv, id = "dataset") %>% janitor::clean_names()
# 
# d$type <- ifelse( grepl("SPLICING", d$dataset), "splicing", "expression")
# d$tissue <- "DLPFC (Common Mind)"


results_files <- list.files(here::here("TWAS/"), pattern = "fusion_res", full.names = TRUE, recursive = TRUE)
results_files <- results_files[c(1,4)]
names(results_files) <- basename(results_files)

all_res <- map_df(results_files, ~{
  read_tsv(.x)  %>%
    mutate(twas_fdr = p.adjust(TWAS.P, method = "BH"),
           twas_bonferroni = p.adjust(TWAS.P, method = "bonferroni"))
  }, .id = "dataset" ) %>%
  janitor::clean_names()

all_res$QTL <- gsub(".fusion_res.tsv", "",str_split_fixed(all_res$dataset, "\\.", 2)[,2])

all_res$type <- ifelse( grepl("SPLICING|sQTL", all_res$QTL), "sQTL", "eQTL")
all_res$tissue <- gsub("_", " ", gsub("NYGC|_sQTL|_SPLICING", "", all_res$QTL) )

all_res <- all_res %>% 
  mutate(gene = case_when(
  grepl("chr", id) ~ str_split_fixed(id, ":", 4)[,4],
  TRUE ~ id ) ) %>%
  mutate( abs_z = abs(twas_z))

all_res <- mutate( all_res,
  type = ifelse(type == "eQTL", "expression", "splicing"),
  tissue = case_when(
    tissue == "CMC.BRAIN.RNASEQ" ~ "DLPFC (CMC)",
    tissue == "AMPAD TWAS" ~ "DLPFC (AMP-AD)",
    tissue == "Brain Cortex" ~ "DLPFC (GTEx)", 
    tissue == "Brain Cerebellum" ~ "Cerebellum (GTEx)")
  )
#all_res$QTL <- basename(dirname(all_res$file) )

# group_by(all_res, QTL, sig = twas_fdr < 0.05) %>%
#   summarise( n = n() ) %>%
#   filter(sig == TRUE) %>%
#   arrange(desc(n))

table(all_res$twas_fdr < 0.05) # 82 associations

```


```{r}
make_z_plot <- function(data){
  gwas_order <- filter(data, twas_bonferroni < 0.05) %>% 
    ungroup() %>%
    select(best_gwas_id, best_gwas_z) %>% distinct() %>%
    arrange(desc(best_gwas_z)) %>%
    filter( !duplicated(best_gwas_id))
  
  #return(gwas_order)
  
  hits <- filter(data, twas_bonferroni < 0.05)
  
  #print(hits)
  
  data %>%
  filter(id %in% unique(hits$id) ) %>%
  mutate(best_gwas_id = factor(best_gwas_id, levels = gwas_order$best_gwas_id)) %>%
  ggplot(aes(x = tissue, y = gene)) + geom_tile(aes(fill = twas_z)) +
  scale_fill_distiller(type = "div" ) +
    facet_grid(best_gwas_id ~ ., scales = "free_y",space = "free_y" ) +
    theme_bw() +
    theme(strip.text.y = element_text(angle = 0, colour = "black", hjust = 0.5), 
          strip.text.x = element_text(angle = 0, colour = "black", face = "bold"), 
          axis.text.x = element_text(angle = 45, hjust = 1, colour = "black"), 
          axis.text.y = element_text(face = "italic", colour = "black"),
          strip.background = element_blank(), 
          legend.position = "top",
          legend.box.margin = margin(c(0,0,0,0)), 
          legend.margin = margin(c(0,0,0,0)),
          strip.placement = "outside",
          panel.spacing.y = unit(x = 0,units = "points"), panel.border = element_rect(fill = NA, size = 0.2, colour = "black"), 
          panel.spacing.x = unit(x = 0,units = "points"),
          panel.grid = element_blank(),
          axis.ticks = element_line(colour = "black")
          ) +
    scale_size_continuous(limits = c(0,1)) +
    scale_alpha_continuous(limits = c(0,1)) +
    guides(size = "none", alpha = "none") +
    scale_x_discrete(position = "bottom") +
    labs(x = "", y = "", colour = "Tissue")
}




# get largest abs Z-score for each gene in each panel

best_z_res <- all_res %>%
  #filter(grepl("NYGC|CMC", QTL) ) %>%
  group_by(tissue, panel, gene) %>%
  summarise( abs_z = max(abs_z) ) %>%
  left_join(all_res)




best_z_res %>% make_z_plot( )
```


```{r}
make_manhattan <- function(d, bh = 0.05, expression_only = TRUE){
  
  ymax <- max(d$twas_z,na.rm=T)+0.5
  ymin <- min(d$twas_z,na.rm=T)-0.5

  Sig_Z_Thresh <- qnorm(1-(0.05/length(d$twas_z))/2)
  
  d <- ungroup(d)
  
  d <- arrange( d, chr, p0)
  d <- as.data.frame(d)
  d$pos <- NA
    ticks <- NULL
    lastbase <- 0
    numchroms <- length(unique(d$chr))

    for (i in unique(d$chr)) {
      if (i==1) {
        d[d$chr==i, ]$pos = d[d$chr==i, ]$p0
      } else {
        lastbase=lastbase + tail(subset(d,chr==i-1)$p0, 1)
        d[d$chr==i, ]$pos <- d[d$chr==i, ]$p0+lastbase
      }
      ticks <- c(ticks, d[d$chr==i, ]$pos[floor(length(d[d$chr==i, ]$pos)/2)+1])
    }
    
    ticklim=c(min(d$pos),max(d$pos))

    mycols=rep(c("gray35","gray72"),60)
  chr_labs <- as.character(unique(d$chr))
    chr_labs[chr_labs == '19'| chr_labs == '21']<-' '
  if(expression_only){
    d <- filter(d, type == "expression")
  }
    
  d %>%
  ggplot(aes(x = pos, y = twas_z)) + 
  ggrastr::rasterise(geom_point(aes(colour = factor(chr) ), size = 0.3 ), dpi = 600 ) +
  geom_text_repel(data = filter(d, twas_bonferroni < bh), aes(x = pos, y = twas_z, label = gene), fontface = "italic" ) + 
  geom_point(data = filter(d, twas_bonferroni < bh, type == "expression"), colour = "forestgreen", size = 1) + 
  #geom_point(data = filter(d, twas_bonferroni < bh, type == "splicing"), colour = "blue", size = 1) + 
  facet_wrap(~tissue, ncol = 1) +
  theme_classic() + 
  scale_x_continuous(name="Chromosome", breaks=ticks, labels=chr_labs) +
    scale_y_continuous(name='Z score',limits=c(ymin,ymax)) +
  scale_colour_manual(values=mycols, guide=FALSE) +
  theme(strip.background = element_blank(), 
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.line = element_blank(),
        strip.text.x = element_text(face = "bold" ),
        axis.text = element_text(colour = "black"),
        axis.ticks = element_line(colour = "black")
        )
}

twas_multiplot <- best_z_res %>% make_manhattan()


twas_multiplot

ggsave(plot = twas_multiplot, width = 9, height = 6, filename = here::here("figures/TWAS_plot.pdf"))


twas_genes <- all_res %>% filter(twas_bonferroni < 0.05) %>% pull(gene)
twas_table <- filter(all_res, gene %in% twas_genes)

write_tsv(twas_table, file = here::here("TWAS/twas_results_BH_0.05.tsv"))

twas_z_table <-
twas_table %>%
  select(gene, chr, best_gwas_id, tissue, twas_z) %>%
  pivot_wider(names_from = "tissue", values_from = "twas_z") %>%
  arrange(chr)

write_tsv(twas_z_table, here::here("TWAS/twas_Z_scores_BH_0.05.tsv") )

```

